import Navigation from "../components/Navigation";

export default function privacyPolicy() {
  return (
    <div className=" bg-albyYellow-300 min-h-screen grid place-items-center relative">
      <div className="w-[93.194%] mx-auto ">
        <Navigation />
        <div className="xl:mt-20 mt-22 lg:mt-0 flex flex-col lg:flex-row items-center lg:items-[inherit] justify-between font-secondary">
          <div id="doc" style={{width: "50%", margin: "0 auto"}} className="markdown-body container-fluid comment-inner comment-enabled" data-hard-breaks="true">
            <h1 className="lg:text-2xl text-xl font-normal" id="Data-protection-notice" data-id="Data-protection-notice"><span>Data protection notice</span></h1><p><a href="http://getalby.com" target="_blank" rel="noopener noreferrer"><span>getalby.com</span></a><span> (hereinafter “Alby” or “We” or “Us”) welcomes you to our internet page and browser extension (together also referred to as “Online Offers”). We thank you for your interest in our company and our products.</span></p><p><strong><span>1. Alby respects your privacy</span></strong></p><p><span>The protection of your privacy throughout the course of processing personal data as well as the security of all business data are important concerns to us. We process personal data that was gathered during your visit of our Online Offers confidentially and only in accordance with statutory regulations.</span><br />
              <span>Data protection and information security are included in our corporate policy.</span></p><p><strong><span>2. Controller</span></strong><br />
              <span>Alby is the controller responsible for the processing of your data; exceptions are outlined in this data protection notice.</span><br />
              <span>Our contact details are as follows: Moritz Kaminski, </span><a href="mailto:moritz@getalby.com" target="_blank" rel="noopener noreferrer"><span>moritz@getalby.com</span></a></p><p><strong><span>3. Collection, processing and usage of personal data</span></strong></p><p><span>3.1 Processed categories of data</span><br />
              <span>Communication data, transaction data, lightning node authentication data are processed</span></p><p><span>3.2 Principles</span><br />
              <span>Personal data consists of all information related to an identified or identifiable natural person, this includes, e.g. names, addresses, phone numbers, email addresses, contractual master data, contract accounting and payment data, which is an expression of a person’s identity.</span><br />
              <span>We collect, process and use personal data (including IP addresses) only when there is either a statutory legal basis to do so or if you have given your consent to the processing or use of personal data concerning this matter, e.g. by means of registration.</span></p><p><span>3.3. Processing purposes and legal basis</span><br />
              <span>We as well as the service providers commissioned by us; process your personal data for the following processing purposes:</span></p><p><span>3.3.1 Provision of these Online Offers</span><br />
              <span>Legal basis: Legitimate interest as long as this occurs in accordance with data protection and competition law.</span></p><p><span>3.3.2 Resolving service disruptions as well as for security reasons.</span><br />
              <span>Legal basis: Fulfillment of our legal obligations within the scope of data security and legitimate interest in resolving service disruptions as well as in the protection of our offers.</span></p><p><span>3.3.3 Self-promotion and promotion by others as well as market research and reach analysis done within the scope statutorily permitted or based on consent.</span><br />
              <span>Legal basis: Consent or legitimate interest on our part in direct marketing if in accordance with data protection and competition law.</span></p><p><span>3.3.4 Product or customer surveys performed via email and/or telephone subject to your prior express consent.</span><br />
              <span>Legal basis: Consent</span></p><p><span>3.3.5 Sending an email or SMS/MMS newsletter subject to the recipient’s consent</span><br />
              <span>Legal basis: Consent.</span></p><p><span>3.3.6 Safeguarding and defending our rights.</span><br />
              <span>Legal basis: Legitimate interest on our part for safeguarding and defending our rights.</span></p><p><span>3.4 Log files</span><br />
              <span>Each time you use the internet, your browser is transmitting certain information which we store in so-called log files.</span><br />
              <span>We store log files to determine service disruptions and for security reasons (e.g., to investigate attack attempts) for a period of 60 days and delete them afterwards. Log files which need to be maintained for evidence purposes are excluded from deletion until the respective incident is resolved and may, on a case-by-case basis, be passed on to investigating authorities.</span></p><p><span>Log files are also used for analysis purposes (without the IP address or without the complete IP address) see module “Advertisements and/or market research (including web analysis, no customer surveys)”.</span><br />
              <span>In log files, the following information is saved:</span></p><ul>
              <li><span>IP address (internet protocol address) of the terminal device used to access the Online Offer;</span></li>
              <li><span>Internet address of the website from which the Online Offer is accessed (so-called URL of origin or referrer URL);</span></li>
              <li><span>Name of the service provider which was used to access the Online Offer;</span></li>
              <li><span>Name of the files or information accessed;</span></li>
              <li><span>Date and time as well as duration of recalling the data;</span></li>
              <li><span>Amount of data transferred;</span></li>
              <li><span>Operating system and information on the internet browser used, including add-ons installed (e.g., Flash Player);</span></li>
              <li><span>http status code (e.g., “Request successful” or “File requested not found”).</span></li>
            </ul><p><span>3.5 Children</span><br />
              <span>This Online Offer is not meant for children under 16 years of age.</span></p><p><span>3.6 Data transfer</span></p><p><span>3.6.1 Data transfer to other controllers</span><br />
              <span>Principally, your personal data is forwarded to other controllers only if required for the fulfillment of a contractual obligation, or if we ourselves, or a third party, have a legitimate interest in the data transfer, or if you have given your consent. Particulars on the legal basis and the recipients or categories of recipients can be found in the Section – Processing purposes and legal basis. Additionally, data may be transferred to other controllers when we are obliged to do so due to statutory regulations or enforceable administrative or judicial orders.</span></p><p><span>3.6.2 Service providers (general)</span><br />
              <span>We involve external service providers with tasks such as sales and marketing services, contract management, payment handling, programming, data hosting     . We have chosen those service providers carefully and monitor them on a regular basis, especially regarding their diligent handling of and protection of the data that they store. All service providers are obliged to maintain confidentiality and to comply with the statutory provisions.</span></p><p><span>3.6.3 Transfer to recipients outside the EEA</span><br />
              <span>We might transfer personal data to recipients located outside the EEA into so-called third countries. In such cases, prior to the transfer we ensure that either the data recipient provides an appropriate level of data protection or that you have consented to the transfer. You are entitled to receive an overview of third country recipients and a copy of the specifically agreed-provisions securing an appropriate level of data protection. For this purpose, please use the statements made in the Contact section.</span></p><p><span>3.7 Duration of storage, retention periods</span><br />
              <span>Principally, we store your data for as long as it is necessary to render our Online Offers and connected services or for as long as we have a legitimate interest in storing the data. In all other cases we delete your personal data with the exception of data we are obliged to store for the fulfillment of legal obligations (e.g. due to retention periods under the tax and commercial codes we are obliged to have documents such as contracts and invoices available for a certain period of time).</span></p><p><strong><span>4. Usage of Cookies</span></strong></p><p><span>In the context of our online service, cookies and tracking mechanisms may be used. Cookies are small text files that may be stored on your device when visiting our online service. Tracking is possible using different technologies. In particular, we process information using pixel technology and/or during log file analysis.</span></p><p><span>4.1 Categories</span><br />
              <span>We distinguish between cookies that are mandatorily required for the technical functions of the online service and such cookies and tracking mechanisms that are not mandatorily required for the technical function of the online service.</span><br />
              <span>It is generally possible to use the online service without any cookies that serve non-technical purposes.</span></p><p><span>4.1.1 Technically required cookies</span><br />
              <span>By technically required cookies we mean cookies without those the technical provision of the online service cannot be ensured.</span><br />
              <span>Such cookies will be deleted when you leave the website.</span></p><p><span>4.1.2 Cookies and tracking mechanisms that are technically not required</span><br />
              <span>We only use cookies and tracking mechanisms if you have given us your prior consent in each case. With the exception of the cookie that saves the current status of your privacy settings (selection cookie). This cookie is set based on legitimate interest.</span><br />
              <span>We distinguish between two sub-categories with regard to these cookies and tracking mechanisms:</span></p><p><span>4.1.3 Comfort cookies</span><br />
              <span>These cookies facilitate operation and thus allow you to browse our online service more comfortably; e.g. your language settings may be included in these cookies.</span></p><p><span>4.2 Management of cookies and tracking mechanisms</span><br />
              <span>You can manage your cookie and tracking mechanism settings in the browser</span><br />
              <span>Note: The settings you have made refer only to the browser used in each case.</span></p><p><span>4.2.1 Deactivation of all cookies</span><br />
              <span>If you wish to deactivate all cookies, please deactivate cookies in your browser settings. Please note that this may affect the functionality of the website.</span></p><p><strong><span>5. Data processing by App Store operators</span></strong><br />
              <span>We do not collect data, and it is beyond our responsibility, when data, such as username, email address and individual device identifier are transferred to an app store (e.g., Google Web Store, Firefox Add-ons) when downloading the respective application. We are unable to influence this data collection and further processing by the App Store as controller.</span></p><p><strong><span>6. Communication tools on social media platforms</span></strong><br />
              <span>We use on our social media platform (e.g. twitter) communication tools to process your messages sent via this social media platform and to offer you support.</span><br />
              <span>When sending a message via our social media platform the message is processed to handle your query (and if necessary additional data, which we receive from the social media provider in connection with this message as your name or files).</span><br />
              <span>In addition we can analyze these data in an aggregated and anonymized form in order to better understand how our social media platform is used.</span><br />
              <span>The legal basis for the processing of your data is our legitimate interest (Art. 6 para. 1 s. 1 lit. f GDPR) or, if applicable, an existing contractual relationship (Art. 6 para. 1 s. 1 lit. b GDPR).</span></p><p><strong><span>7. Newsletter with opt-in; Right of withdrawal</span></strong><br />
              <span>Within the scope of our Online Offers you can sign up for newsletters. We provide the so-called double opt-in option which means that we will only send you a newsletter via email, mobile messenger (such as, e.g. WhatsApp), SMS or push notification after you have explicitly confirmed the activation of the newsletter service to us by clicking on the link in a notification. In case you wish to no longer receive newsletters, you can terminate the subscription at any time by withdrawing your consent. You can withdraw your consent to email newsletters by clicking on the link which is sent in the respective newsletter mail, or in the administrative settings of the online offer. Alternatively, please contact us via the contact details provided in the Contact section.</span></p><p><strong><span>8. External links</span></strong><br />
              <span>Our Online Offers may contain links to internet pages of third parties, in particular providers who are not related to us. Upon clicking on the link, we have no influence on the collecting, processing and use of personal data possibly transmitted by clicking on the link to the third party (such as the IP address or the URL of the site on which the link is located) as the conduct of third parties is naturally beyond our control. We do not assume responsibility for the processing of personal data by third parties.</span></p><p><strong><span>9. Security</span></strong><br />
              <span>Our employees and the companies providing services on our behalf, are obliged to confidentiality and to compliance with the applicable data protection laws.</span><br />
              <span>We take all necessary technical and organizational measures to ensure an appropriate level of security and to protect your data that are administrated by us especially from the risks of unintended or unlawful destruction, manipulation, loss, change or unauthorized disclosure or unauthorized access. Our security measures are, pursuant to technological progress, constantly being improved.</span></p><p><strong><span>10. User rights</span></strong><br />
              <span>To enforce your rights, please use the details provided in the Contact section. In doing so, please ensure that an unambiguous identification of your person is possible.</span></p><p><span>10.1 Right to information and access</span><br />
              <span>You have the right to obtain confirmation from us about whether or not your personal data is being processed, and, if this is the case, access to your personal data.</span></p><p><span>10.2 Right to correction and deletion</span><br />
              <span>You have the right to obtain the rectification of inaccurate personal data.  As far as statutory requirements are fulfilled, you have the right to obtain the completion or deletion of your data.</span><br />
              <span>This does not apply to data which is necessary for billing or accounting purposes or which is subject to a statutory retention period. If access to such data is not required, however, its processing is restricted (see the following).</span></p><p><span>10.3 Restriction of processing</span><br />
              <span>As far as statutory requirements are fulfilled you have the right to demand for restriction of the processing of your data.</span></p><p><span>10.4 Data portability</span><br />
              <span>As far as statutory requirements are fulfilled you may request to receive data that you have provided to us in a structured, commonly used and machine-readable format or – if technically feasible –that we transfer those data to a third party.</span></p><p><span>10.5 Right of objection</span><br />
              <span>10.5.1 Objection to direct marketing</span><br />
              <span>Additionally, you may object to the processing of your personal data for direct marketing purposes at any time. Please take into account that due to organizational reasons, there might be an overlap between your objection and the usage of your data within the scope of a campaign which is already running.</span></p><p><span>10.5.2 Objection to data processing based on the legal basis of “legitimate interest”</span><br />
              <span>In addition, you have the right to object to the processing of your personal data at any time, insofar as this is based on “legitimate interest”. We will then terminate the processing of your data, unless we demonstrate compelling legitimate grounds according to legal requirements which override your rights.</span></p><p><span>10.6 Withdrawal of consent</span><br />
              <span>In case you consented to the processing of your data, you have the right to revoke this consent at any time with effect for the future. The lawfulness of data processing prior to your withdrawal remains unchanged.</span></p><p><span>10.7 Right to lodge complaint with supervisory authority:</span><br />
              <span>You have the right to lodge a complaint with a supervisory authority. You can appeal to the supervisory authority which is responsible for your place of residence or your state of residency or to the supervisory authority responsible for us.</span><br />
              <span>This is:</span><br />
              <span>Federal Commissioner for Data Protection and Information</span><br />
              <span>Feldeggweg 1</span><br />
              <span>CH - 3003 Bern</span><br />
              <span>Schweiz</span><br />
              <span>Telefon: +41 (0)58 462 43 95</span><br />
              <span>Homepage: </span><a href="http://www.edoeb.admin.ch" target="_blank" rel="noopener noreferrer"><span>http://www.edoeb.admin.ch</span></a></p><p><strong><span>11. Changes to the Data Protection Notice</span></strong><br />
              <span>We reserve the right to change our security and data protection measures. In such cases, we will amend our data protection notice accordingly. Please, therefore, notice the current version of our data protection notice, as this is subject to changes.</span></p><p><strong><span>12. Contact</span></strong><br />
              <span>If you wish to contact us, please find us at the address stated in the “Controller” section.</span></p><p><span>Effective date: 2021.11.03</span></p>
          </div>
        </div>
      </div>
    </div>
  );
}
